# Generated by Django 6.0.2 on 2026-02-25 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.area'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('HVAC', 'HVAC'), ('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Housekeeping', 'Housekeeping'), ('Carpentry', 'Carpentry'), ('STP/WTP', 'STP/WTP'), ('Safety', 'Safety'), ('Security', 'Security'), ('Parking', 'Parking'), ('other', 'other')], max_length=50),
        ),
    ]
